---
# tasks file for yum_cron

- name: Load variables.
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
    - "default.yml"

- name: Enable rhel-7-server-optional-rpms repository
  rhsm_repository:
    name: rhel-7-server-optional-rpms
    state: enabled
  when:
    ansible_distribution == 'RedHat' and ansible_distribution_major_version == '7'

- name: Install packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    "{{ yum_cron__packages }}"

- name: Select hourly config
  set_fact:
    yum_cron__config: "{{ yum_cron__hourly }}"

- name: Manage hourly yum-cron-hourly.conf
  template:
    src: "yum-cron.conf.j2"
    dest: "{{ yum_cron__hourly_config }}"
    mode: 0644
    owner: root
    group: root
  notify:
    - restart yum-cron

- name: Select daily config
  set_fact:
    yum_cron__config: "{{ yum_cron__daily }}"

- name: Manage daily yum-cron.conf
  template:
    src: "yum-cron.conf.j2"
    dest: "{{ yum_cron__daily_config }}"
    mode: 0644
    owner: root
    group: root
  notify:
    - restart yum-cron

- block:
    - name: Download latest Centos errata.
      get_url:
        url: "{{ yum_cron__centos_errata_url }}"
        dest: /tmp/updateinfo.xml
        mode: 0440
    - name: Add errata to updates repo
      command: /usr/bin/modifyrepo --simple-md-filenames /tmp/updateinfo.xml "{{ yum_cron__centos_updates_repo }}"
      args:
        creates: "{{ yum_cron__centos_updates_repo }}/updateinfo.xml.gz"
    - name: Cron job to download errata daily.
      cron:
        name: CentOS Errata
        special_time: daily
        user: root
        job: "/usr/bin/wget -qN -P/tmp {{ yum_cron__centos_errata_url }} && /usr/bin/modifyrepo --simple-md-filenames /tmp/updateinfo.xml {{ yum_cron__centos_updates_repo }} > /dev/null"
        cron_file: CentOS_Errata
  when: ansible_distribution == 'CentOS'
